//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meter_Readings
    {
        public int AccountId { get; set; }
        public System.DateTime MeterReadingDateTime { get; set; }
        public double MeterReadValue { get; set; }
    
        public virtual Test_Accounts Test_Accounts { get; set; }
    }
}
